  framework:
    container_name: framework
    ports:
      - 8000
    volumes:
      - ./framework:/framework
    build:
      context: framework
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY=$FRAMEWORK_SECRET_KEY
      - DEBUG=$FRAMEWORK_DEBUG
      - ALLOWED_HOSTS=$FRAMEWORK_ALLOWED_HOSTS
      - USE_S3=$FRAMEWORK_USE_S3
      - AWS_ACCESS_KEY_ID=$FRAMEWORK_AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$FRAMEWORK_AWS_SECRET_ACCESS_KEY
      - AWS_STORAGE_BUCKET_NAME=$FRAMEWORK_AWS_STORAGE_BUCKET_NAME
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
    command:
      "gunicorn --workers=2 --bind=0.0.0.0:8000 --reload framework.wsgi:application"
